replicaCount: 2

image:
  repository: ghcr.io/ileahu-ellation/crunchygram-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8081
  targetPort: 3000

volumes:
  - name: data
    hostPath:
      path: "/home/ubuntu/crgram-data"

volumeMounts:
  - name: data
    mountPath: "/usr/src/app/data"
