replicaCount: 3

image:
  repository: ghcr.io/ileahu-ellation/crunchygram-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  ports:
    - port: 80
      containerPort: 3000

volumes:
  - name: data
    hostPath:
      path: "/home/ubuntu/crgram-data"

volumeMounts:
  - name: data
    mountPath: "/usr/src/app/data"
